-- 初始设置
Aki.DB = {
	autoSell = true,
	solo = {
		ownInterrupt = 'self',
		ownInterruptSound = '',
		ownDispel = 'self',
		ownDispelSound = '',
		ownStolen = 'self',
		ownStolenSound = '',
		ownReflect = 'self',
		ownReflectSound = '',
	},
	instance = {
		ownInterrupt = 'self',
		ownInterruptSound = '',
		ownDispel = 'self',
		ownDispelSound = '',
		ownStolen = 'self',
		ownStolenSound = '',
		ownReflect = 'self',
		ownReflectSound = '',
		otherInterrupt = 'self',
		otherInterruptSound = '',
		otherDispel = 'self',
		otherDispelSound = '',
		otherStolen = 'self',
		otherStolenSound = '',
		otherReflect = 'self',
		otherReflectSound = '',
	},
	party = {
		ownInterrupt = 'self',
		ownInterruptSound = '',
		ownDispel = 'self',
		ownDispelSound = '',
		ownStolen = 'self',
		ownStolenSound = '',
		ownReflect = 'self',
		ownReflectSound = '',
		otherInterrupt = 'self',
		otherInterruptSound = '',
		otherDispel = 'self',
		otherDispelSound = '',
		otherStolen = 'self',
		otherStolenSound = '',
		otherReflect = 'self',
		otherReflectSound = '',
	},
	raid = {
		ownInterrupt = 'self',
		ownInterruptSound = '',
		ownDispel = 'self',
		ownDispelSound = '',
		ownStolen = 'self',
		ownStolenSound = '',
		ownReflect = 'self',
		ownReflectSound = '',
		otherInterrupt = 'self',
		otherInterruptSound = '',
		otherDispel = 'self',
		otherDispelSound = '',
		otherStolen = 'self',
		otherStolenSound = '',
		otherReflect = 'self',
		otherReflectSound = '',
	},
}

--所有音效列表
Aki.soundList = {
	'', '关',
	566564, 'Bell 1',
	565853, 'Bell 2',
	839999, 'Ice Shard',
	623880, 'Impact',
	565875, 'Orb Explode',
	569673, 'Pet Call',
	542499, 'Roar Dwarf',
	542504, 'Roar Orc',
	644480, 'Swoosh',
	539153, 'Whistle',
}